version: '3.9'
services:
  masterdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${MASTER_DB_USER}
      - POSTGRES_PASSWORD=${MASTER_DB_PASS}
      - POSTGRES_DB=${MASTER_DB_NAME}
    ports:
      - "${MASTER_DB_PORT}:5432"
    volumes:
      - ./data/devdb:/var/lib/postgresql/data
    networks:
      - dev
  mailer:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_MAIL_PORT}:1025"
      - "${MAILHOG_PORT}:8025"
    networks:
      - dev
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dev
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "${KAFKA_DROP_PORT}:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    volumes:
      - ./data/kafdrop:/var/lib/kafdrop
    networks:
      - dev
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "${KAFKA_PORT_1}:2181"
      - "${KAFKA_PORT_2}:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:${KAFKA_PORT_2}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_PORT_2}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka:/var/lib/kafka
    networks:
      - dev
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: "no"
    command: ./meilisearch --master-key=${MEILISEARCH_MASTER_KEY}
    volumes:
      - ./data/meilisearch:/var/lib/data.ms
    ports:
      - ${MEILISEARCH_PORT}:7700
    networks:
      - dev

networks:
  dev:
    driver: bridge
